### ISSUE TITLE
Publish date?

### ISSUE THREAD

**Issue by iamrajee** [tum-vision/tandem#1]
Hi, Thank you for the awesome work. I'm curious as to when would you be open-sourcing source code of underline method? Thanks!

**Comment by lkskstlr** [comment]
Hi, @iamrajee, thank you very much for the kind words. I am currently still at CoRL where the paper is being presented and have deadlines in the next weeks. I hope to release first parts of the code/data in November and everything until latest Christmas. Thank you for your patience:)

**Comment by iamrajee** [comment]
Sure, thank you for the update :)
