### ISSUE TITLE
Cudatoolkit couldn't find

### ISSUE THREAD

**Issue by Bobkk-k** [tum-vision/tandem#26]
Hi, 

I installed CUDAToolkit 11.1.0 as per the nvidia official website. When I ran nvcc -V, the terminal displayed the text in the first 

image. I believe It means the installation is complete. However, when I ran 'cmake ..', an error happened(the second image).

Can anyone help me solve this problem?

Thank you!
![image](https://user-images.githubusercontent.com/78141973/165749428-ea29f46c-78b6-4064-980e-07edb15e7030.png)

![image](https://user-images.githubusercontent.com/78141973/165750452-e594d69a-729b-455d-9c22-2246ad3d1364.png)

**Comment by three-nine** [comment]
Hi, have you solved this problem? I have the same problem too.

**Comment by Bobkk-k** [comment]
Hi @three-nine,
Sorry to say I don't know how to solve it. If you find the method, please tell me. Thanks!

**Comment by Bobkk-k** [comment]
Hi  @three-nine ,
I changed my cmake version and the error disappeared.

**Comment by three-nine** [comment]
@Bobkk-k Thank you very much!

**Comment by wenmoqiu** [comment]
Hi @Bobkk-k ,
What is your cmake version? Mine is 3.16 but it didn't work
