### ISSUE TITLE
make error about Sophus

### ISSUE THREAD

**Issue by Bobkk-k** [tum-vision/tandem#27]
make error about Sophus

![image](https://user-images.githubusercontent.com/78141973/167604704-0c8b62a4-f653-4531-8de7-03aa0926a524.png)

When I fellow  the readme in the Sophus folder to make Sophus, something that looks likes make fail appeared.

![image](https://user-images.githubusercontent.com/78141973/167604596-b3134f58-659d-4928-8fa6-50670d7f1655.png)

Does anyone know how to solve it ?
Thanks!

**Comment by Bobkk-k** [comment]
I changed the 'Sophus::SE3 <double>' in the error file to 'Sophus::SE3d' and the error disappeared

**Comment by jarvis-huang** [comment]
Correction => should be to change **`Sophus::SE3<double>`** to **`Sophus::SE3d`**. Its definition is [here](https://github.com/tum-vision/tandem/blob/master/tandem/thirdparty/Sophus/sophus/se3.hpp#L36).
