### ISSUE TITLE
NO PHOTOMETRIC Calibration!

### ISSUE THREAD

**Issue by HJMGARMIN** [tum-vision/tandem#33]
When I run tracking_euroc.bash, I get an error below.

ERROR: dont't have photometric calibation. Need to use commandline options mode=1 or mode=2 The run took 0 seconds which includes warm-up and loading.

**Comment by three-nine** [comment]
Hi, sorry to trouble you.I am a beginner in this field. Can you tell me the version of pangolin and cmake you use and how to install pangolin? I failed when using make -j in version 0.5.When I used version 0.6 ,it would report an error that Pangolin cannot be found in the tandem. This problem has bothered me for a long time. I hope you can help me.
