### ISSUE TITLE
Can run without any visual window

### ISSUE THREAD

**Issue by aax1n** [tum-vision/tandem#35]
(https://user-images.githubusercontent.com/91367508/176985320-60ae95da-2216-4fe6-8f83-53faa045151d.png)

**Comment by three-nine** [comment]
Hi,sorry to bother you.Can you tell me when you finished 'make -j' what you do next?Is it to execute 'build/bin/tandem_dataset' directly?Thank you very much!

**Comment by 1974685090** [comment]
Yes， run 'build/bin/tandem_dataset'directly

**Comment by aax1n** [comment]
Yes， run 'build/bin/tandem_dataset'directly @three-nine

**Comment by three-nine** [comment]
@1974685090 Thanks!

**Comment by three-nine** [comment]
Hi,  sorry to bother you again.   Have you used your owned dataset to train successfully?

**Comment by zhangjd1029** [comment]
> Hi, sorry to bother you again. Have you used your owned dataset to train successfully?
Have you run your own dataset yet? I've been making segmentation fault
