### ISSUE TITLE
Install Sophus from thirdparty folder,but compile error

### ISSUE THREAD

**Issue by w8128835** [tum-vision/tandem#50]
hello,I installed the sophus in thirdparty folder ,but I met a problem like this picture when I use make -j10 to build the project.Do you know how to solve it ?
![image](https://user-images.githubusercontent.com/31956796/221196160-e0452e90-bf00-4ee4-bda6-57a97f062188.png)

**Comment by Victorrr1** [comment]
maybe this is due to the change in template of SE3.
"Sophus::SE3<double> SE3"modify to "Sophus::SE3d SE3"may works

**Comment by w8128835** [comment]
@Victorrr1 sorry for late reply,I forget to close this issue.I deleted template <double>,and it works. Thank you very much.
