### ISSUE TITLE
Convention of the Coordiante System / Representation of Poses

### ISSUE THREAD

**Issue by geoeo** [tum-vision/tandem#55]
I couldn't find anything about this.

1) What do the poses in the pose file represent? Is it the pose of the camera in world coordinates w.r.t some other point(origin) also in world coordinates?

E.g. Origin is at (0,0,0) and the first Camera is at (2,0,0) then cam_world is simply the translation (2,0,0)?

2) What Coordinate System should the poses be in? Is it Camera Coordinates i.e. +X - Right, +Y Down, +Z Into the image / Does it matter?

**Comment by ShuhongLL** [comment]
Hello, did you figure out the coordinate system? I am facing the same problem. Thanks in advance

**Comment by geoeo** [comment]
@ShuhongLL Poses should be in Camera Coordinates i.e +X - Right, +Y Down, +Z Into the image. 
Input pose file doesnt matter iirc the framework will tranform the poses such that the middle camera is the origin
